-- Trace les jokers payés via Stripe (10 € pour débloquer un indice).
-- Adaptez les types de aventure_id/indice_id si vos tables "Aventures"
-- et "Indices" n'utilisent pas des identifiants bigint par défaut.
create table if not exists public."Jokers" (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id),
  aventure_id bigint not null,
  indice_id bigint not null,
  session_id text not null unique,
  paid boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public."Jokers" enable row level security;

-- Chaque utilisateur ne voit que ses propres jokers. Les insertions ne
-- passent que par le webhook Stripe (clé service_role, qui contourne la RLS).
create policy "Les utilisateurs voient leurs propres jokers"
  on public."Jokers"
  for select
  using (auth.uid() = user_id);
